name: Build Electron App with Yarn

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [14.x] # Adjust the Node version as needed
    name: Build on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install -g yarn # This step can be adjusted or removed if not necessary
      - name: Install Dependencies
        run: yarn install
      - name: Build and Package App
        run: yarn build && yarn package
        env:
          CI: true